### PR TITLE
Robustify linear algebra operations

### PR DESCRIPTION
**Pull request by timmens**

### CODE REVIEW

**Comment by timmens** [comment]
Very sorry, it's early in the morning and I did not check the default base branch! I wanted to merge into my forked repo... Love your package though!

**Comment by mwt** [comment]
Great to see another Econ PhD student here! I'm going on the market next year. So, I probably won't be working on this package for a while. I have a long list of desired features including CI for conda/pip, testing speedups with cython, and several others. If you want to contribute to the package, there's plenty to do! I know you didn't intend to submit this. Still, it gets me thinking.

I would not want forcing invertibility for `ktril` to be a default because the fact that diagonal elements are not zero is the main assumption of the Volterra inversion theorem. It would be good as an option though. Something like `ensure_unique=false` or `allow_singular=true`.

However, making diagonal elements nearly zero sounds like it would send values near infinity. It might work better to add some epsilon multiplied by the `Hmat` used in the Fredholm function (lines 78-80 of fredholm.py). This `Hmat` leverages continuity of the solution. It should make reasonable solutions. This would make the matrix non-triangular. So, you'd need to use the regular inversion.

It might also work to use `numpy.linalg.pinv` to get the smallest solution when the matrix is singular. This has the advantage of returning one of the actual solutions to the system. None of the entries will be arbitrarily large as well (since you're getting the smallest solution). I don't think there's any guarantee that the solution would be smooth though.

It's also probably possible to write an optimization routine that always converges to a smooth solution. Maybe gradient descent with steps that are biased to be smooth? There's probably an existing algorithm out there that solves this problem.

Are you using this package for a problem with a weakly singular kernel? I know there is a literature on computing these, but I don't know much about it.

**Comment by timmens** [comment]
Hey! Thanks for the very detailed response. :)

Those are great tips and I already used them. Thank you! For context, we are trying to estimate a functional parameter in a functional data setting. But now we've decided to pursue a different route using a slightly more complex model which does not allow us to use these standard integral equations, at least I think so. However, using your package we were able to estimate the parameter in the simpler case :tada: 

Good luck on the job market next year! If I ever have a free weekend (do they even exist in academia?) I may offer some help with the CI and speed-up stuff. I can definitely recommend numba and jax, at least that's what our group here is using primarily.

**Comment by mwt** [comment]
That sounds very cool! Yeah, any nonlinear integral equation or one with more than two parameters would probably be completely different.

**Pull request closed without merging**
